---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          imagePullPolicy: Always
          image: 039454511521.dkr.ecr.us-east-1.amazonaws.com/app:v0.0.0
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: COLOR